source "https://rubygems.org"

gem "minima", "~> 2.5"
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Jekyll seems to depend on erb, but not install it
gem "erb"